_target_: diffusers.DDPMScheduler
num_train_timesteps: 1000
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "squaredcos_cap_v2"
variance_type: "fixed_small"
clip_sample: false
prediction_type: 'sample'
